export { Pagination } from './src/components/pagination'
export { config, text, seoText } from './src/utils/config'
export { Page } from './src/templates/page-template'

export {
  Box,
  Fade,
  Toggle,
  Move,
  LetterFade,
  LetterFade2,
  Zoom,
  ZoomPanic,
  Show,
  Peek,
  Shadow,
  domprogress,
  useCss,
  useFlexMasonry,
  useGridMasonry,
  useLocalStorage,
  useScript,
  useWindowResize,
  Spinner01,
  Switch,
  SocialShare,
  Disqus,
  CodeLink,
  useCodePenScript,
  CodePen,
  Highlight,
  apply_highlight,
  BImg,
  Img,
  fixDate,
  shuffle_array,
  is_this_a_mobile_device,
  wait,
  get_response,
  get_request,
  Prism,
  GoogleMap,
  Instagram,
  Pinterest,
  PinterestScript,
  Video,
  Youtube,
  SEO,
} from 'gatsby-theme-kuworking-methods'
