export { Pagination } from './src/components/pagination'
export { config, text, seoText } from './src/utils/config'
export { Page } from './src/templates/page-template'

export {
  SEO,
  Margin,
  q,
  qq,
  Switch,
  Spinner01,
  SocialShare,
  Box,
  Fade,
  Toggle,
  Move,
  Neutral,
  TextLetterFade,
  TextLetterFade2,
  TextPeek,
  TextShadow,
  TextShow,
  TextZoom,
  TextZoomPanic,
  domprogress,
  useCss,
  useFlexMasonry,
  useGridMasonry,
  useLocalStorage,
  useScript,
  useWindowResize,
  useInterval,
  Disqus,
  CodeLink,
  useCodePenScript,
  CodePen,
  Highlight,
  apply_highlight,
  BImg,
  Img,
  fixDate,
  shuffle_array,
  is_this_a_mobile_device,
  wait,
  get_response,
  get_request,
  Prism,
  GoogleMap,
  Instagram,
  Pinterest,
  PinterestScript,
  Video,
  Youtube,
} from 'gatsby-theme-kuworking-methods'
