// implements color themes to be switched

export const colors = {
  cta__div__background: 'linear-gradient(to left,#ffffff,#fafafa)',
  cta__div__border: '#e6e6e6',
  cta__title__color: '#737373',
  cta__em__background: '#ffffff',
  cta__em__color: '#ff6a00',
  cta__button__background: '#ffffff30',
  cta__button__color: '#000',
  cta__button__border: '#000',
  cta__button_hover__background: '#000000',
  cta__button_hover__color: '#fff',

  cards__border: '#e6e6e6',
  cards__background: '#fff',
  cards__title__background: '',
  cards__title__color: '#fff',
  cards__title_em__background: '#ffffff52',
  cards__abstract_em__background: '#dad9d352',

  post__title__color: '#ff5c3a',
  post__title_em__color: '#ffffff',
  post__title_em__background: '#dedede',
  post__tags__info__color: '#a1a1a1',
  post__tags__tag__color: '#757575',
  post__tags__tag__background: '#ccc',
  post__tags__tag_hover__color: '#ffffff',
  post__tags__tag_hover__background: '#616161',
  post__comments__background: '#ececec',
  post__comments__title__color: '#3d2c29',
  post__comments_hover__background: '#989898',
  post__comments_hover__title__color: '#fff',

  text: '#3d2c29',
  em__text: '#3d2c29',
  em__background: '#c7c7c7',
  code: '#3d2c29',
  code__background: '#f1b0b0',
  blockquote__background: '#eaeaea',
  heading: '#444444',
  link: '#ff6a00',
  linkOver: '#79cdff',
  background: '#fafafa',

  primary: '#000',
  secondary: '#000',
  accent: '#000',
  muted: '#000',

  modes: {
    dark: {
      cta__div__background: 'linear-gradient(52deg, rgb(34, 38, 57) 60%, rgb(111, 66, 183) 80%, rgb(52, 0, 130) 100%)',
      cta__div__border: '#fff',
      cta__title__color: '#c969dc',
      cta__em__background: '#ffed70',
      cta__em__color: '#000000',
      cta__button__background: '#ffffff30',
      cta__button__color: '#fff',
      cta__button__border: '#fff',
      cta__button_hover__background: '#ff9191',
      cta__button_hover__color: '#fff',

      cards__border: '#fff',
      cards__background: '#000',
      cards__title__background: '',
      cards__title__color: '#fff',
      cards__title_em__background: '#ffffff52',
      cards__abstract_em__background: '#ffffff52',

      post__title__color: '#c1a2ff',
      post__title_em__color: '#000000',
      post__title_em__background: '#8776b1',
      post__tags__info__color: '#a1a1a1',
      post__tags__tag__color: '#757575',
      post__tags__tag__background: '#ccc',
      post__tags__tag_hover__color: '#ffffff',
      post__tags__tag_hover__background: '#616161',
      post__comments__background: '#191919',
      post__comments_hover__background: '#616161',
      post__comments_hover__title__color: '#989898',

      text: '#F0F5FA',
      em__text: '#F0F5FA',
      em__background: '#c7c7c7',
      code: '#3d2c29',
      code__background: '#c58f8f',
      blockquote__background: '#616161',
      heading: '#d9d7dc',
      link: '#ff6a00',
      linkOver: '#79cdff',
      background: '#000000',

      primary: '#fff',
      secondary: '#fff',
      accent: '#fff',
      muted: '#fff',
    },
  },
}

export const modes = ['light', 'dark']
